export const ADD_PRODUCT = 'ADD_PRODUCT'
export const ADD_PRODUCT_SUCC = 'ADD_PRODUCT_SUCC'
export const ADD_PRODUCT_ERR = 'ADD_PRODUCT_ERR'

export const START_DOWNLOAD_PRODUCTS = 'START_DOWNLOAD_PRODUCTS'
export const DOWNLOAD_PRODUCTS_SUCC = 'DOWNLOAD_PRODUCTS_SUCC'
export const DOWNLOAD_PRODUCTS_ERR = 'DOWNLOAD_PRODUCTS_ERR'

export const GET_DELETED_PRODUCT = 'GET_DELETED_PRODUCT'
export const DELETED_PRODUCT_SUCC = 'DELETED_PRODUCT_SUCC'
export const DELETED_PRODUCT_ERR = 'DELETED_PRODUCT_ERR'

export const GET_EDIT_PRODUCT = 'GET_EDIT_PRODUCT'
export const EDIT_PRODUCT_SUCC = 'EDIT_PRODUCT_SUCC'
export const EDIT_PRODUCT_ERR = 'EDIT_PRODUCT_ERR'
export const EDIT_BEGIN = 'EDIT_BEGIN'

export const SHOW_ALERT = 'SHOW_ALERT'
export const HIDE_ALERT = 'HIDE_ALERT'
